### ISSUE TITLE
VVV 2.2.0

### ISSUE THREAD

**Issue by benlumia007** [Varying-Vagrant-Vagrants/VVV#1500]
@tomjn

Do you guys have the original source code for the 2.2.0. This version, I have been using a while and it works perfectly  and since the master develop is 2.2.1 has issues and it seems like 2.2.1 vagrantfile request >2.1.1 or something. 

I was reading some issues prior and saw that vagrant 2.2.1 and vvv 2.1 has problems working together so I had to downgrade to vagrant 2.0.4 and seems  like i need to use vvv 2.2.0 instead of 2.2.1 

Trying to go back to the following components that works for me

Vagrant: 2.0.4
VVV: 2.2.0
Windows 10.

**Comment by tomjn** [comment]
@benlumia007 it should be here on GitHub if you checkout the specific commit just before the Vagrant core changes

Can you raise issues for the current `develop` version so we can fix them? If it's the nginx server certificate that's been fixed just now. Going forward we'll be requiring Vagrant 2.1 as a minimum

**Comment by benlumia007** [comment]
@tomjn 

Hey man, thanks for the update, I still have a laptop that has Vagrant 2.1 and VVV 2.2.1 I'll do some testing, I remember it failed right is about to create a custom template (sandbox) and it exited and it said something. 

[The SSH command responded with a non-zero exit status. Vagrant assumes that this means the command failed. The output for this command should be in the log above. Please read the output to determine what went wrong.]

**Comment by benlumia007** [comment]
@tomjn: yes, it looks like its the certifcate issue that you were describing. 

default: nginx: [emerg] BIO_new_file("/vagrant/certificates/sandbox/dev.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/vagrant/certificates/sandbox/dev.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
    default: nginx: configuration file /etc/nginx/nginx.conf test failed

Is there a way to fix this or have u come out with a fix for it,

My current setup right now is

Vagrant 2.1.0
VVV: 2.2.1
Windows 10 (Version 1803)

**Comment by tomjn** [comment]
@benlumia007 It was fixed before I made my last reply, and should not be an issue in the current `develop` branch

**Comment by benlumia007** [comment]
@tomjn 
It looks like I'm using the develop branch but is getting that error at this moment even if you fixed the problem.

**Comment by benlumia007** [comment]
@tomjn 
When I first clone this develop branch, I went ahead and did a `vagrant up --provision` and it give me that certificate issue and did a another `vagrant provision` and it still failed

```
  default: nginx: [emerg] BIO_new_file("/vagrant/certificates/sandbox/dev.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/vagrant/certificates/sandbox/dev.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
    default: nginx: configuration file /etc/nginx/nginx.conf test failed
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
so most likely, doing another re-provisioning did not work.

**Comment by tomjn** [comment]
hmm that is not an error I have seen before, @LoreleiAurora thoughts?

**Comment by tomjn** [comment]
As an aside, can you produce a full provision log?

**Comment by benlumia007** [comment]
@tomjn 
What version for box are you guys on, i wonder if it could be the box it self, im using the latest version 
ubuntu/trusty64 (virtualbox, 20180509.0.0)

**Comment by benlumia007** [comment]
I'm also getting this too 
` default: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")
`

**Comment by benlumia007** [comment]
also, do you remember the last commit number that was changed before 2.2.1

**Comment by tomjn** [comment]
You shouldn't update the vagrant box, not while we're on VVV 2, I'm debugging

**Comment by benlumia007** [comment]
I know, just that some of my computers are using different boxes since some laptops i use more and less,  

I eventually tested an older version of Windows 10 (1709) and still have the same problem. so we can rule out the windows 10 (1709) and (1803).

**Comment by tomjn** [comment]
@benlumia007 you can get that by clicking on `commits` on the main repo page, but there is no canonical `2.2.0`, you're going to have to check individual commits, starting with the one immediatley before the vagrant trigger core changes

**Comment by tomjn** [comment]
@benlumia007 can you try the `tomjn_fixes` branch?

**Comment by benlumia007** [comment]
@tomjn 
for sure, I'll give that a shot.

**Comment by benlumia007** [comment]
@tomjn 
Looks like it worked, vagrant 2.1.1  with tomjn_fixes works cool

**Comment by benlumia007** [comment]
@guyromellemagayano 
It works if you delete the .vangrant.d on Windows platform because that's what i did and it fixed the problem. I have used tomjn_fixes on two different computers running windows and I'm about to test another windows platform.  It works fine. 

keep develop branch separate from tomjn_fixes in a separate folder

**Comment by guyromellemagayano** [comment]
@benlumia007 

I see. My VVV setup is currently installed in my Mac with the latest High Sierra update. Will try your suggestion and let you know my findings. 👍

**Comment by tomjn** [comment]
A possible reason is because one of the changesets that caused issues moved logs to `/srv/log`

Since some stuff still goes to `/var/log` I moved it all back in that branch, then changed the vagrant mapping to use `/var/log` rather than `/srv/log` as it's got more stuff in it, to consolidate things

It's likely that all that needs adding is `noroot mkdir -p /var/log/nginx && noroot touch /var/log/nginx/error.log` to `provision.sh` though I don't know why this would be an issue now when it wasn't before, `v2.1` has the same log location

**Comment by tomjn** [comment]
@benlumia007 it should work now, I spoke with @LoreleiAurora and we merged it and a revert to another PR that should fix grunt, I'm reprovisioning from scratch now and conducting tests

@guyromellemagayano I've made a modification that should ensure the nginx log files are created if they don't exist and the relevant folders are present, let me know if the `develop` branch resolves that issue for you

**Comment by benjaminlu007** [comment]
@tomjn 
Should I go ahead and test the develop branch since @LoreleiAurora did a merge 14 minutes ago. 

just a note if anyone is having issues, im using the following

Vagrant 2.1.1
VVV 2.2.1 (Last Commit May 14, 2018, Merge #1505) 
Windows 10 Home/Pro

Thanks Guys

**Comment by benlumia007** [comment]
ha keep using the wrong account

@tomjn
Should I go ahead and test the develop branch since @LoreleiAurora did a merge 14 minutes ago.

just a note if anyone is having issues, im using the following

Vagrant 2.1.1
VVV 2.2.1 (Last Commit May 14, 2018, Merge #1505)
Windows 10 Home/Pro

Thanks Guys

**Comment by benlumia007** [comment]
@tomjn 
So i have provisioned as well on 4 different computers now and it seems to work flawlessly. no error logs or the original problem with the SSH, looks like it has been fixed.

**Comment by tomjn** [comment]
Awesome, I'm going to close this out and continue testing
