### ISSUE TITLE
GPG error: public key not available for package cloud.io

### ISSUE THREAD

**Issue by hphioolen** [Varying-Vagrant-Vagrants/VVV#1701]
## Expected Behavior

Vagrant up should work

## Current Behavior

Vagrant up fails on error:
GPG error: https://packagecloud.io trusty InRelease: The following signatures couldn't be verified because the public key is not available:

## Steps to Reproduce (for bugs)

started on a fresh install on MacOS 10.13.6
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v2.4.0-git::master

Platform:   darwin13.4.0 shell:/bin/bash
Vagrant:    2.2.2
VirtualBox: 6.0.0r127566

https://gist.github.com/hphioolen/1bcb2a55f2e03f37856c5a4522b9a427

## Your Environment

* VVV version: 2.4.0
* VVV Git Branch: 
master
* Vagrant version: 2.2.2
* VM Provider name: Virtualbox
* VM Provider version: 6.0.0
* Operating System and version: MacOS 10.13.6

**Comment by tomjn** [comment]
This looks to be related to #1700,

**Comment by tomjn** [comment]
can you test https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1702 ? It should resolve the issue, but I want to be sure, then I can make an emergency release

**Comment by hphioolen** [comment]
It seems that this is the issue, I'm jest not sure how to fix it. 
I'm guessing this should solve it:

> For APT repositories: Use apt-key to import the repository’s new GPG key. Be sure to substitute the user and repository in this example before running it: curl -L https://packagecloud.io/user/repository/gpgkey | apt-key add -. You will need to be root to run this command. 

But what are user and repository in this? And should I run this on my local machine or on the vagrant box?

**Comment by tomjn** [comment]
Try the pull request I opened, it replaces the keys as needed

**Comment by tomjn** [comment]
@hphioolen I just merged the pull request with a fix, can you confirm the fix fixes it? It's in the `develop` branch now

**Comment by georgewalish** [comment]
@tomjn I had this same issue and your fix in the <code>develop</code> branch worked. Thank You!

**Comment by enkrates** [comment]
What is the timeline for this fix to make it into `master`? I'm still seeing the bug there and I'm weighing switching to `develop` to get the fix.

**Comment by tomjn** [comment]
there aren't many differences between `master` and `develop` at the moment, mostly bug fixes. I'm hoping to do a release before the end of the week but I'm ill at the moment so I don't have a lot of energy to get stuff done

**Comment by enkrates** [comment]
Thanks for all the work you do on this project and please don't rush on my account. I'll happily wait for you to find the time to merge. 😄
