### ISSUE TITLE
"Aw shoot, XHGui hit an error"

### ISSUE THREAD

**Issue by pressoholics** [Varying-Vagrant-Vagrants/VVV#2261]
Having issues with the XHGui Profiler. Get the "Aw shoot, XHGui hit an error": https://share.getcloudapp.com/yAulrl4d

Setup details:

- MacOS 10.14.6
- Fresh install (Tried both stable and develop branches as of this ticket issue date)
- Site based on custom-site-template.git
- Tried all versions of php7 (reprovisioning between changes)
- Tried destroying vagrant
- Get this error with tideways_on and tideways_off commands

Error details:

could not find driver

You should check the following things:

- Ensure that Mongo has been started
- That config/config.php has the right connection information.
- That the cache/ directory has the correct permissions.

Stack Trace
```
#0 /srv/www/default/xhgui/src/Xhgui/ServiceContainer.php(129): PDO->__construct('sqlite:/tmp/xhg...', NULL, NULL, Array)
#1 /srv/www/default/xhgui/vendor/pimple/pimple/src/Pimple/Container.php(118): XHGui\ServiceContainer::XHGui\{closure}(Object(XHGui\ServiceContainer))
#2 /srv/www/default/xhgui/src/Xhgui/ServiceContainer.php(134): Pimple\Container->offsetGet('pdo')
#3 /srv/www/default/xhgui/vendor/pimple/pimple/src/Pimple/Container.php(118): XHGui\ServiceContainer::XHGui\{closure}(Object(XHGui\ServiceContainer))
#4 /srv/www/default/xhgui/src/Xhgui/ServiceContainer.php(142): Pimple\Container->offsetGet('XHGui\\Db\\PdoRep...')
#5 /srv/www/default/xhgui/vendor/pimple/pimple/src/Pimple/Container.php(118): XHGui\ServiceContainer::XHGui\{closure}(Object(XHGui\ServiceContainer))
#6 /srv/www/default/xhgui/src/Xhgui/ServiceContainer.php(148): Pimple\Container->offsetGet('searcher.pdo')
#7 /srv/www/default/xhgui/vendor/pimple/pimple/src/Pimple/Container.php(118): XHGui\ServiceContainer::XHGui\{closure}(Object(XHGui\ServiceContainer))
#8 /srv/www/default/xhgui/src/Xhgui/ServiceContainer.php(185): Pimple\Container->offsetGet('searcher')
#9 /srv/www/default/xhgui/vendor/pimple/pimple/src/Pimple/Container.php(114): XHGui\ServiceContainer::XHGui\{closure}(Object(XHGui\ServiceContainer))
#10 /srv/www/default/xhgui/src/routes.php(41): Pimple\Container->offsetGet('runController')
#11 [internal function]: {closure}()
#12 /srv/www/default/xhgui/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#13 /srv/www/default/xhgui/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route->dispatch()
#14 /srv/www/default/xhgui/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#15 /srv/www/default/xhgui/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#16 /srv/www/default/xhgui/vendor/slim/slim/Slim/Middleware/SessionCookie.php(110): Slim\Middleware\MethodOverride->call()
#17 /srv/www/default/xhgui/src/Xhgui/Middleware/RenderMiddleware.php(14): Slim\Middleware\SessionCookie->call()
#18 /srv/www/default/xhgui/vendor/slim/slim/Slim/Slim.php(1300): XHGui\Middleware\RenderMiddleware->call()
#19 /srv/www/default/xhgui/webroot/index.php(13): Slim\Slim->run()
#20 {main}
```

Any help or advice would be awesome!

Thanks again for the amazing work on this.

**Comment by Mte90** [comment]
Seems that there are some issues with sqlite...
I will investigate

**Comment by pressoholics** [comment]
just another point when using php 7.3/7.4 I also see this error when enalbing xdebug or tideways via terminal:

WARNING: Module tideways_xhprof ini file doesn't exist under /etc/php/7.4/mods-available

full output:
vagrant@vvv:~$ tideways_off
 * Disabling active debug PHP mods
 * Disabling if present: 'xdebug, xhgui, tideways_xhprof, pcov'
 * Disabling active module: 'tideways_xhprof'
WARNING: Module tideways_xhprof ini file doesn't exist under /etc/php/7.4/mods-available
WARNING: Module tideways_xhprof ini file doesn't exist under /etc/php/7.4/mods-available
 * Restarting PHP FPM's so the change takes effect

**Comment by Mte90** [comment]
On xhgui.vvv.test I am getting:
```
#0 /srv/www/default/xhgui/src/Xhgui/Db/PdoRepository.php(90): PDO->prepare('\n          SELE...')
#1 /srv/www/default/xhgui/src/Xhgui/Searcher/PdoSearcher.php(108): XHGui\Db\PdoRepository->countByUrl('')
#2 /srv/www/default/xhgui/src/Xhgui/Controller/RunController.php(48): XHGui\Searcher\PdoSearcher->getAll(Array)
#3 /srv/www/default/xhgui/src/routes.php(45): XHGui\Controller\RunController->index(Object(Slim\Http\Request), Object(Slim\Http\Response))
#4 [internal function]: {closure}()
#5 /srv/www/default/xhgui/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#6 /srv/www/default/xhgui/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route->dispatch()
#7 /srv/www/default/xhgui/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#8 /srv/www/default/xhgui/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#9 /srv/www/default/xhgui/vendor/slim/slim/Slim/Middleware/SessionCookie.php(110): Slim\Middleware\MethodOverride->call()
#10 /srv/www/default/xhgui/src/Xhgui/Middleware/RenderMiddleware.php(14): Slim\Middleware\SessionCookie->call()
#11 /srv/www/default/xhgui/vendor/slim/slim/Slim/Slim.php(1300): XHGui\Middleware\RenderMiddleware->call()
#12 /srv/www/default/xhgui/webroot/index.php(13): Slim\Slim->run()
#13 {main}
```

So In my opinion there is an error with the sqlite file generated, I am checking it.

**Comment by Mte90** [comment]
If I execute Tideways and open a page with tideways running the error is different.
I think that I found some bugs in XHgui, I am reporting them.

**Comment by tomjn** [comment]
perhaps this would be best done via #2251

**Comment by Mte90** [comment]
Everything is fixed by xhgui now and works (I tested).
You need a provision.

**Comment by tomjn** [comment]
@pressoholics can you reprovision and confirm things are working? @Mte90 where did the fix occur?

**Comment by Mte90** [comment]
The fix was required in various part of XHGUI itself.

**Comment by pressoholics** [comment]
Sorry guys, i've pulled from develop branch, destroyed and re-provisioned. still getting errors on XHGui page:

Aw shoot, XHGui hit an error
could not find driver

You should check the following things:

Ensure that Mongo has been started
That config/config.php has the right connection information.
That the cache/ directory has the correct permissions.

`#0 /srv/www/default/xhgui/src/Xhgui/ServiceContainer.php(129): PDO->__construct('sqlite:/tmp/xhg...', NULL, NULL, Array)
#1 /srv/www/default/xhgui/vendor/pimple/pimple/src/Pimple/Container.php(118): XHGui\ServiceContainer::XHGui\{closure}(Object(XHGui\ServiceContainer))
#2 /srv/www/default/xhgui/src/Xhgui/ServiceContainer.php(134): Pimple\Container->offsetGet('pdo')
#3 /srv/www/default/xhgui/vendor/pimple/pimple/src/Pimple/Container.php(118): XHGui\ServiceContainer::XHGui\{closure}(Object(XHGui\ServiceContainer))
#4 /srv/www/default/xhgui/src/Xhgui/ServiceContainer.php(142): Pimple\Container->offsetGet('XHGui\\Db\\PdoRep...')
#5 /srv/www/default/xhgui/vendor/pimple/pimple/src/Pimple/Container.php(118): XHGui\ServiceContainer::XHGui\{closure}(Object(XHGui\ServiceContainer))
#6 /srv/www/default/xhgui/src/Xhgui/ServiceContainer.php(148): Pimple\Container->offsetGet('searcher.pdo')
#7 /srv/www/default/xhgui/vendor/pimple/pimple/src/Pimple/Container.php(118): XHGui\ServiceContainer::XHGui\{closure}(Object(XHGui\ServiceContainer))
#8 /srv/www/default/xhgui/src/Xhgui/ServiceContainer.php(185): Pimple\Container->offsetGet('searcher')
#9 /srv/www/default/xhgui/vendor/pimple/pimple/src/Pimple/Container.php(114): XHGui\ServiceContainer::XHGui\{closure}(Object(XHGui\ServiceContainer))
#10 /srv/www/default/xhgui/src/routes.php(41): Pimple\Container->offsetGet('runController')
#11 [internal function]: {closure}()
#12 /srv/www/default/xhgui/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#13 /srv/www/default/xhgui/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route->dispatch()
#14 /srv/www/default/xhgui/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#15 /srv/www/default/xhgui/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#16 /srv/www/default/xhgui/vendor/slim/slim/Slim/Middleware/SessionCookie.php(110): Slim\Middleware\MethodOverride->call()
#17 /srv/www/default/xhgui/src/Xhgui/Middleware/RenderMiddleware.php(14): Slim\Middleware\SessionCookie->call()
#18 /srv/www/default/xhgui/vendor/slim/slim/Slim/Slim.php(1300): XHGui\Middleware\RenderMiddleware->call()
#19 /srv/www/default/xhgui/webroot/index.php(13): Slim\Slim->run()
#20 {main}`

**Comment by Mte90** [comment]
I don't have that issue, can you try on deleting the folder in `www/default/xhgui` and provision again?

**Comment by tomjn** [comment]
I'm reopening this for now so it's easier to find, though it looks like a different but related issue to what was originally reported

**Comment by Mte90** [comment]
I am able to replicate the issue, I am on it.

**Comment by Mte90** [comment]
Ok seems that you don't have the sqlite package for php installed.
Remove the `/www/default/php-profiler` folder and do a new provision.

**Comment by pressoholics** [comment]
ok, getting closer: http://xhgui.vvv.test/

Error:
SQLSTATE[HY000]: General error: 1 no such table: results

You should check the following things:

Ensure that Mongo has been started
That config/config.php has the right connection information.
That the cache/ directory has the correct permissions.

Stack Trace:
`#0 /srv/www/default/xhgui/src/Xhgui/Db/PdoRepository.php(90): PDO->prepare('\n          SELE...')
#1 /srv/www/default/xhgui/src/Xhgui/Searcher/PdoSearcher.php(108): XHGui\Db\PdoRepository->countByUrl('')
#2 /srv/www/default/xhgui/src/Xhgui/Controller/RunController.php(48): XHGui\Searcher\PdoSearcher->getAll(Array)
#3 /srv/www/default/xhgui/src/routes.php(45): XHGui\Controller\RunController->index(Object(Slim\Http\Request), Object(Slim\Http\Response))
#4 [internal function]: {closure}()
#5 /srv/www/default/xhgui/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#6 /srv/www/default/xhgui/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route->dispatch()
#7 /srv/www/default/xhgui/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#8 /srv/www/default/xhgui/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#9 /srv/www/default/xhgui/vendor/slim/slim/Slim/Middleware/SessionCookie.php(110): Slim\Middleware\MethodOverride->call()
#10 /srv/www/default/xhgui/src/Xhgui/Middleware/RenderMiddleware.php(14): Slim\Middleware\SessionCookie->call()
#11 /srv/www/default/xhgui/vendor/slim/slim/Slim/Slim.php(1300): XHGui\Middleware\RenderMiddleware->call()
#12 /srv/www/default/xhgui/webroot/index.php(13): Slim\Slim->run()
#13 {main}`

**Comment by Mte90** [comment]
This was a bug fixed in xhgui, I thinkthat removing the xhgui folder and a provision should be enough but also the pr in progress should fix any other issue remaining.

**Comment by pressoholics** [comment]
ok

Just a little more info:

when i make a request with the param: ?enable-tideways=1

I get this error:
Undefined variable: direction

`
#0 /srv/www/default/xhgui/src/Xhgui/Searcher/PdoSearcher.php(116): Slim\Slim::handleErrors(8, 'Undefined varia...', '/srv/www/defaul...', 116, Array)

#1 /srv/www/default/xhgui/src/Xhgui/Controller/RunController.php(48): XHGui\Searcher\PdoSearcher->getAll(Array)

#2 /srv/www/default/xhgui/src/routes.php(45): XHGui\Controller\RunController->index(Object(Slim\Http\Request), Object(Slim\Http\Response))

#3 [internal function]: {closure}()

#4 /srv/www/default/xhgui/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)

#5 /srv/www/default/xhgui/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route->dispatch()

#6 /srv/www/default/xhgui/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()

#7 /srv/www/default/xhgui/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()

#8 /srv/www/default/xhgui/vendor/slim/slim/Slim/Middleware/SessionCookie.php(110): Slim\Middleware\MethodOverride->call()

#9 /srv/www/default/xhgui/src/Xhgui/Middleware/RenderMiddleware.php(14): Slim\Middleware\SessionCookie->call()

#10 /srv/www/default/xhgui/vendor/slim/slim/Slim/Slim.php(1300): XHGui\Middleware\RenderMiddleware->call()

#11 /srv/www/default/xhgui/webroot/index.php(13): Slim\Slim->run()

#12 {main}`

**Comment by Mte90** [comment]
This is something fixed with https://github.com/perftools/xhgui/issues/349 so you need to remove the `www/default/xhgui` that I guess is not updating with the provisioner.

**Comment by pressoholics** [comment]
Sadly still not working.

I removed www/default/xhgui and /www/default/php-profiler and reprovisioned.

Also tried destroying the machine, also tested on stable and develop branch (both just reprovision and destroying machine).

No longer get the errors above on the xhgui landing page, but it doesn't record any data when using the ?enable-tideways=1 URL param. I did ssh in and run tideways_on before hand.

If you navigate to the Waterfall tab in XHGui there are some errors:

Undefined index: page

You should check the following things:

Ensure that Mongo has been started
That config/config.php has the right connection information.
That the cache/ directory has the correct permissions.

Stack trace

`#0 /srv/www/default/xhgui/src/Xhgui/Searcher/PdoSearcher.php(101): Slim\Slim::handleErrors(8, 'Undefined index...', '/srv/www/defaul...', 101, Array)

#1 /srv/www/default/xhgui/src/Xhgui/Controller/WaterfallController.php(36): XHGui\Searcher\PdoSearcher->getAll(Array)

#2 /srv/www/default/xhgui/src/routes.php(196): XHGui\Controller\WaterfallController->index()

#3 [internal function]: {closure}()

#4 /srv/www/default/xhgui/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)

#5 /srv/www/default/xhgui/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route->dispatch()

#6 /srv/www/default/xhgui/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()

#7 /srv/www/default/xhgui/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()

#8 /srv/www/default/xhgui/vendor/slim/slim/Slim/Middleware/SessionCookie.php(110): Slim\Middleware\MethodOverride->call()

#9 /srv/www/default/xhgui/src/Xhgui/Middleware/RenderMiddleware.php(14): Slim\Middleware\SessionCookie->call()

#10 /srv/www/default/xhgui/vendor/slim/slim/Slim/Slim.php(1300): XHGui\Middleware\RenderMiddleware->call()

#11 /srv/www/default/xhgui/webroot/index.php(13): Slim\Slim->run()

#12 {main}`

**Comment by Mte90** [comment]
This seems again a XHGUI bug, I will open a ticket about it

**Comment by pressoholics** [comment]
was this addressed in this ticket?

[Undefined index: page perftools/xhgui#369](https://github.com/perftools/xhgui/issues/369)

**Comment by pressoholics** [comment]
update:

The error on the waterfall page 'http://xhgui.vvv.test/waterfall' has no gone.

But the main issue of not recording any profile data still remains.

* ran tideways_on
* added ?enable-tideways=1 to urls

Has anyone else reported a similar issue with not recording profile data?

I'm using PHP 7.4, is tideways no supported fully on php 7.4?

**Comment by Mte90** [comment]
It seems again a xhgui bug, the sqlite file has the content but the PDO of xhgui doesn't get anything.

Reported on https://github.com/perftools/xhgui/issues/371

**Comment by Mte90** [comment]
Bug fixed I can see again the stuff inside xhgui, just do a provision!

**Comment by Mte90** [comment]
There is also an update to the utility so now use a specific version to avoid those issues.
